### ISSUE TITLE
Stacktrace when analysing nvs

### ISSUE THREAD

**Issue by crasu** [AFontaine79/Espressif-NVS-Analyzer#2]
When running this on my dumped esp32 nvs I get the following error:

```
Traceback (most recent call last):
  File "/home/christian/projects/Growatt_ShineWiFi-S/SRC/ShineWiFi-ModBus/./analyze_nvs.py", line 368, in <module>
    main()
  File "/home/christian/projects/Growatt_ShineWiFi-S/SRC/ShineWiFi-ModBus/./analyze_nvs.py", line 350, in main
    parse_nvs_binary(input)
  File "/home/christian/projects/Growatt_ShineWiFi-S/SRC/ShineWiFi-ModBus/./analyze_nvs.py", line 276, in parse_nvs_binary
    scan_in_page(input[page_base:page_base+PAGE_SIZE], page_idx)
  File "/home/christian/projects/Growatt_ShineWiFi-S/SRC/ShineWiFi-ModBus/./analyze_nvs.py", line 226, in scan_in_page
    namespace_name = ns_idx_to_name[entry_ns]

```

**Comment by orzel** [comment]
I got the same, and also another one :
```
    entry_key = entry_key_data.decode('ascii')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'ascii' codec can't decode byte 0x94 in position 1: ordinal not in range(128)

```
